version: '3.8'

services:
  activemq:
    image: apache/activemq-artemis:2.33.0
    container_name: activemq-artemis
    hostname: activemq
    restart: unless-stopped
    environment:
      ARTEMIS_USER_FILE: /run/secrets/activemq_user
      ARTEMIS_PASSWORD_FILE: /run/secrets/activemq_password
      ARTEMIS_MIN_MEMORY: 512M
      ARTEMIS_MAX_MEMORY: 2G
      ENABLE_JMX: 'true'
      ENABLE_JMX_RMI: 'true'
    ports:
      - "61616:61616"   # ARTEMIS port
      - "8161:8161"     # Web console
      - "5672:5672"     # AMQP
      - "1883:1883"     # MQTT
      - "61613:61613"   # STOMP
    volumes:
      - activemq_data:/var/lib/artemis-instance/data
      - activemq_logs:/var/lib/artemis-instance/log
      - ./config/broker.xml:/var/lib/artemis-instance/etc/broker.xml:ro
      - ./config/artemis.profile:/var/lib/artemis-instance/etc/artemis.profile:ro
      - ./config/bootstrap.xml:/var/lib/artemis-instance/etc/bootstrap.xml:ro
      - ./config/jolokia-access.xml:/var/lib/artemis-instance/etc/jolokia-access.xml:ro
    secrets:
      - activemq_user
      - activemq_password
    networks:
      - activemq_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8161/console/login || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2.5G
          cpus: '1.0'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.activemq.rule=Host(`activemq.localhost`)"
      - "traefik.http.services.activemq.loadbalancer.server.port=8161"

  activemq-classic:
    image: apache/activemq-classic:5.18.3
    container_name: activemq-classic
    hostname: activemq-classic
    restart: unless-stopped
    profiles:
      - classic
    environment:
      ACTIVEMQ_ADMIN_LOGIN_FILE: /run/secrets/activemq_user
      ACTIVEMQ_ADMIN_PASSWORD_FILE: /run/secrets/activemq_password
      ACTIVEMQ_CONFIG_DIR: /opt/apache-activemq/conf
      ACTIVEMQ_DATA_DIR: /opt/apache-activemq/data
    ports:
      - "61617:61616"   # OpenWire
      - "8162:8161"     # Web console
      - "5673:5672"     # AMQP
      - "1884:1883"     # MQTT
      - "61614:61613"   # STOMP
    volumes:
      - activemq_classic_data:/opt/apache-activemq/data
      - activemq_classic_logs:/var/log/activemq
      - ./config/activemq-classic.xml:/opt/apache-activemq/conf/activemq.xml:ro
      - ./config/jetty.xml:/opt/apache-activemq/conf/jetty.xml:ro
    secrets:
      - activemq_user
      - activemq_password
    networks:
      - activemq_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8161/admin/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '0.8'

volumes:
  activemq_data:
    driver: local
  activemq_logs:
    driver: local
  activemq_classic_data:
    driver: local
  activemq_classic_logs:
    driver: local

networks:
  activemq_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24

secrets:
  activemq_user:
    file: ./secrets/activemq_user.txt
  activemq_password:
    file: ./secrets/activemq_password.txt
