version: '3.8'

services:
  kong-database:
    image: postgres:15-alpine
    container_name: kong-database
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${KONG_PG_USER:-kong}
      - POSTGRES_DB=${KONG_PG_DATABASE:-kong}
      - POSTGRES_PASSWORD_FILE=/run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    volumes:
      - kong_postgres_data:/var/lib/postgresql/data
    networks:
      - kong-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KONG_PG_USER:-kong}"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong-migrations:
    image: kong/kong-gateway:3.4.2
    container_name: kong-migrations
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PORT=5432
      - KONG_PG_USER=${KONG_PG_USER:-kong}
      - KONG_PG_DATABASE=${KONG_PG_DATABASE:-kong}
      - KONG_PG_PASSWORD_FILE=/run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    command: kong migrations bootstrap
    networks:
      - kong-network
    depends_on:
      - kong-database
    restart: "no"

  kong:
    image: kong/kong-gateway:3.4.2
    container_name: kong
    restart: unless-stopped
    ports:
      - "8000:8000"   # Proxy HTTP
      - "8443:8443"   # Proxy HTTPS
      - "8001:8001"   # Admin API HTTP
      - "8444:8444"   # Admin API HTTPS
      - "8002:8002"   # Manager HTTP
      - "8445:8445"   # Manager HTTPS
      - "8003:8003"   # Dev Portal HTTP
      - "8446:8446"   # Dev Portal HTTPS
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PORT=5432
      - KONG_PG_USER=${KONG_PG_USER:-kong}
      - KONG_PG_DATABASE=${KONG_PG_DATABASE:-kong}
      - KONG_PG_PASSWORD_FILE=/run/secrets/kong_postgres_password
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
      - KONG_ADMIN_GUI_API_URL=http://localhost:8001
      - KONG_PORTAL=on
      - KONG_PORTAL_GUI_HOST=localhost:8003
      - KONG_PORTAL_API_URL=http://localhost:8001
    secrets:
      - kong_postgres_password
    volumes:
      - ./config/kong.conf:/etc/kong/kong.conf:ro
    networks:
      - kong-network
    depends_on:
      - kong-database
      - kong-migrations
    healthcheck:
      test: ["CMD-SHELL", "kong health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  konga:
    image: pantsel/konga:0.14.9
    container_name: konga
    restart: unless-stopped
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=${KONGA_ENV:-production}
      - DB_ADAPTER=postgres
      - DB_HOST=kong-database
      - DB_PORT=5432
      - DB_USER=${KONG_PG_USER:-kong}
      - DB_DATABASE=${KONGA_PG_DATABASE:-konga}
      - DB_PASSWORD_FILE=/run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    networks:
      - kong-network
    depends_on:
      - kong-database

secrets:
  kong_postgres_password:
    file: ./secrets/kong_postgres_password.txt

volumes:
  kong_postgres_data:
    driver: local

networks:
  kong-network:
    driver: bridge
