version: '3.8'

# Development version with single MinIO instance
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-01-16T16-07-38Z
    container_name: minio-dev
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER_FILE: /run/secrets/minio_root_user
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_root_password
    volumes:
      - minio_data:/data
      - ./config:/etc/minio:ro
    networks:
      - minio_network
    secrets:
      - minio_root_user
      - minio_root_password
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s

  minio-mc:
    image: quay.io/minio/mc:RELEASE.2024-01-13T08-44-48Z
    container_name: minio-mc-dev
    restart: "no"
    volumes:
      - ./scripts/setup-buckets.sh:/setup-buckets.sh:ro
    networks:
      - minio_network
    secrets:
      - minio_root_user
      - minio_root_password
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: |
      sh -c "
        sleep 5
        /setup-buckets.sh
        echo 'MinIO setup completed!'
      "

volumes:
  minio_data:
    driver: local

networks:
  minio_network:
    driver: bridge

secrets:
  minio_root_user:
    file: ./secrets/minio_root_user.txt
  minio_root_password:
    file: ./secrets/minio_root_password.txt
