version: '3.8'

services:
  cassandra-node1:
    image: cassandra:4.1
    container_name: cassandra-node1
    restart: unless-stopped
    ports:
      - "9042:9042"
      - "7000:7000"
      - "7199:7199"
    environment:
      - CASSANDRA_SEEDS=cassandra-node1
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=128
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=400M
    volumes:
      - cassandra_data_1:/var/lib/cassandra
      - ./config/cassandra.yaml:/etc/cassandra/cassandra.yaml:ro
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - cassandra_network
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  cassandra-node2:
    image: cassandra:4.1
    container_name: cassandra-node2
    restart: unless-stopped
    ports:
      - "9043:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra-node1
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=128
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=400M
    volumes:
      - cassandra_data_2:/var/lib/cassandra
      - ./config/cassandra.yaml:/etc/cassandra/cassandra.yaml:ro
    networks:
      - cassandra_network
    depends_on:
      cassandra-node1:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  cassandra-node3:
    image: cassandra:4.1
    container_name: cassandra-node3
    restart: unless-stopped
    ports:
      - "9044:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra-node1
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack3
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=128
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=400M
    volumes:
      - cassandra_data_3:/var/lib/cassandra
      - ./config/cassandra.yaml:/etc/cassandra/cassandra.yaml:ro
    networks:
      - cassandra_network
    depends_on:
      cassandra-node2:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

volumes:
  cassandra_data_1:
    driver: local
  cassandra_data_2:
    driver: local
  cassandra_data_3:
    driver: local

networks:
  cassandra_network:
    driver: bridge
