version: '3.8'

services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.3
    container_name: redpanda
    hostname: redpanda
    restart: unless-stopped
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --check=false
    ports:
      - "18081:18081"   # Schema Registry
      - "18082:18082"   # REST Proxy (Pandaproxy)
      - "19092:19092"   # Kafka API
      - "19644:9644"    # Admin API
    volumes:
      - redpanda_data:/var/lib/redpanda/data
      - ./config/redpanda.yaml:/etc/redpanda/redpanda.yaml:ro
    networks:
      - redpanda_network
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health --brokers redpanda:9092 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redpanda-console.rule=Host(`redpanda.localhost`)"

  console:
    image: docker.redpanda.com/redpandadata/console:v2.4.1
    container_name: redpanda-console
    hostname: redpanda-console
    restart: unless-stopped
    depends_on:
      redpanda:
        condition: service_healthy
    ports:
      - "8080:8080"     # Console web UI
    environment:
      CONFIG_FILEPATH: /etc/console/config.yml
      KAFKA_BROKERS: redpanda:9092
      KAFKA_SCHEMAREGISTRY_ENABLED: true
      KAFKA_SCHEMAREGISTRY_URLS: http://redpanda:8081
      CONNECT_ENABLED: false
      REDPANDA_ADMINAPI_ENABLED: true
      REDPANDA_ADMINAPI_URLS: http://redpanda:9644
    volumes:
      - ./config/console-config.yml:/etc/console/config.yml:ro
    networks:
      - redpanda_network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/api/cluster || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.3'

  redpanda-rpk:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.3
    container_name: redpanda-rpk
    hostname: redpanda-rpk
    profiles:
      - tools
    depends_on:
      redpanda:
        condition: service_healthy
    networks:
      - redpanda_network
    volumes:
      - ./config:/config:ro
    entrypoint: /bin/bash
    command:
      - -c
      - |
        echo "Redpanda RPK CLI ready. Available commands:"
        echo "- rpk topic list"
        echo "- rpk topic create test-topic"
        echo "- rpk topic produce test-topic"
        echo "- rpk topic consume test-topic"
        echo "- rpk cluster info"
        echo ""
        echo "Example: rpk topic list --brokers redpanda:9092"
        tail -f /dev/null
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.1'

volumes:
  redpanda_data:
    driver: local

networks:
  redpanda_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/24
