cluster.name: "elasticsearch-cluster"
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Security
xpack.security.enabled: true
xpack.security.authc.api_key.enabled: true

# Memory
bootstrap.memory_lock: true

# Discovery
discovery.type: single-node

# Logging
logger.level: INFO
